### ISSUE TITLE
Running multiple servers in a single gulp script

### ISSUE THREAD

**Issue by ccapndave** [gimm/gulp-live-server#13]
I am trying to run gls twice - once to serve some static content, and once to start a restify server on another port.  However, it looks like you can only run one at a time; starting one seems to close the other.  Is this intended behaviour, and if so is there a way around it?

**Comment by gimm** [comment]
Hi @ccapndave, just tried to run two instances of gls, succeed. You need to make sure there's no conflict with the port numbers between these two.
BTW, I don't think it necessary to run two gls, you can serve static content within your rest server without too much pain.

If you insist to run gls twice, please let me know exactly how you run gls twice so I can try to figure the problem here.
thanks for your feedback.

**Comment by LittleHelicase** [comment]
Hey, I had the same problem. I wanted to run two servers in parallel from one gulp script in one gulp task. But the second server always stops the first (as well as the LR). I create a pull request #18 for this.
