### ISSUE TITLE
server.start as watch callback not setting "this"

### ISSUE THREAD

**Issue by horyd** [gimm/gulp-live-server#22]
Using the examples provided, I am encountering the following bug.

When the "myapp.js" file changes, gulp triggers the "server.start" function in the callback. This produces:

```
if (this.server) { // server already running
            ^
TypeError: Cannot read property 'server' of undefined
```

On ln 115 "index.js". Fixed this by explicitely writing the callback as:

```
function () {
  server.start.apply(server);
}
```

Which is similar to how the application of notify method is written.

**Comment by jamesward** [comment]
+1 Same here.

**Comment by gimm** [comment]
Thanks for pointing this out.
I know it's kind of ugly to have `apply` with every method call, I definitely going to restructure the index.js to get rid of `this` reference.

**Comment by niftylettuce** [comment]
:+1:

**Comment by niftylettuce** [comment]
Currently the Readme documentation is not accurate, as the usage of `gulp.watch('app.js', server.start)` is not currently functional due to this issue.

**Comment by bertzzie** [comment]
I have the same issue, and to add some more report:
1. After the process crashed, the current running server is not stopped.
2. This means that I need to manually kill the current process via `kill` so I can run the server again.

Here's the error I'd get if I didn't kill the current process first:

```
events.js:85
      throw er; // Unhandled 'error' event
        ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

Which I could mitigate by first running `ps` and then `kill <pid>`:

```
$ ps
  PID TTY           TIME CMD
  422 ttys000    0:00.06 -bash
 2075 ttys000    0:00.28 /usr/local/bin/node server.js

$ kill 2075
$ gulp serve # now works!
```

I'm not good enough to submit a patch now (because I literally just use gulp-live-serve for the first time (not even an hour)). Hope this helps.

**Comment by poke** [comment]
You should use `gulp.watch('app.js', server.start.bind(server, null))` here. Note the `.bind(server, null)`.

Since `server.start` takes an exec path as an argument, using just `server.start.bind(server)` will not set that. The problem is now that the callback from `gulp.watch` receives an `event` as the first argument. So since our callback is our bound `server.start`, the `event` is passed to `server.start` as the exec path.

Using `server.start.bind(server, null)` explicitly sets the exec path to `null` (so the `gulp.watch` event is passed as the second argument—which is not used), and everything works fine.
