### ISSUE TITLE
Livereload port problem

### ISSUE THREAD

**Issue by veke** [gimm/gulp-live-server#7]
var server = gls('server.js', undefined, livereloadPort);
server.start();

You can control the livereload port number with this, but then you get error from the localhost:
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED

The server.js file is same as in your examples. As a sidenote, app.use(require('connect-livereload')()); in the example server.js is not actually doing anything...not even if you pass a port-number to it like in the connect-livereload documentation. Anyway.

If you say in your instructions, that you can change the port number for livereload, i will expect that things just work. What do you think? If the external server.js file is used with changed livereload port, where the livereload script injection comes from?

**Comment by gimm** [comment]
Hi vennamo,
Just tried exactly what you did, the problem is that the first param for `gls` must be an Array, so `var server = gls(['server.js'], undefined, livereloadPort);` should work for you.

**I've update `gls` to accept single string as first param, so you don't need any change in code if you get the new version.**

You need to pass the port number to connect-livereload if you have a customized one.

The livereload script is injected by `tiny-lr`, it come along with the package.

**Comment by veke** [comment]
Sorry, the example was missing the array...that was not the case.
`var server = gls(['server.js'], undefined, 12345);` that gives the same error if you navigate to localhost:3000 (take a look at browser's console). In server.js file I changed the connect-livereload line too.

```
app.use(require('connect-livereload')({
    port: 12345
}));
```

I have tried different setups. For me this middleware / server / gls / tiny-lr / livereload / connect / server.js etc.. is too much configuring. Not my area of interests. There are many ways to achieve this localhost environment but this time I am looking for the out-of-box easy and fast setup. Yours is super fine with the basic static setting...but is missing this https://github.com/bripkens/connect-history-api-fallback so I need to use external server file (like the one in your example) to extend the functionality. I get also errors with the default livereload port time to time, so Im looking a way to change the default.

I must say that the instructions to use the gls is overtechnical too...im pretty sure most of the people using this are not familiar with these node ChildProcess.spawns etc. but looking for simple examples to configure :)

The livereload part in the instructions is confusing too. It says user needs to take care to get the livereload.js file injected, but if you use static gls setting or external server.js file (even without the connect-livereload-part) the livereload still works. So the options described are falsy. You don't need the plugin, you don't need connect-livereload or manually add the file but instead the injection is handled with this package (using tiny-lr). Like you said "The livereload script is injected by tiny-lr, it come along with the package."

**Comment by gimm** [comment]
My apologize,
The livereload script is ~~injected~~ **served** by tiny-lr, it come along with the package. But the **script tag**  (`<script src="//localhost:12345/livereload.js?snipver=1"></script>`) in the html file is injected by `connect-livereload` or chrome `livereload plugin`, so you do need both configured for a customized port.

I've checked this `history-api-fallback` the first time you mentioned it in previous issue, I can add this support without pain, but it will make configuration more complex, which is not clear already (I'll definitely add examples to make the configuration less confusing). You can achieve the same thing with a external server file, just copy the `static.js`, and add the use for `history-api-fallback`.

I've double checked locally, `gls('server.js', undefined, 12345)` works for me.

If possible, could you share your `server.js` so that I can try to find out the real cause for this?

**Comment by jrschumacher** [comment]
Is there a way to inject this if the server is rendering the app view? Right now I've added this into my html.

```
<!-- build:remove -->
<script src="http://localhost:35729/livereload.js?snipver=1"></script>
<!-- endbuild -->
```
